name: Build Only
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest # The first job utilizes windows-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔨 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

      - name: Upload Artifacts 💾 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v2
        with:
          name: site-artifact
          path: dist
